[package]
name = "gb"
version = "0.1.0"
authors = ["Luka Dornhecker <luka.dornhecker@gmail.com>"]

[dependencies]
libgb = { path = "../libgb" }
env_logger = "*"
log = { version = "*", features = ["std", "release_max_level_debug"] }